<?php

namespace Database\Seeders;

use App\Models\Platform;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PlatformSeeder extends Seeder
{
    const __PLATFORM__ = [
        ["platform_id" => 306, "name" => "Satellaview", "slug" => "satellaview", "generation" => 4, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 339, "name" => "Sega Pico", "slug" => "sega-pico", "generation" => 4, "abbreviation" => null, "alternative_name" => "Kids Computer Pico", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 376, "name" => "Epoch Super Cassette Vision", "slug" => "epoch-super-cassette-vision", "generation" => 3, "abbreviation" => null, "alternative_name" => "YENO Super Cassette Vision", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 62, "name" => "Atari Jaguar", "slug" => "jaguar", "generation" => 5, "abbreviation" => "Jaguar", "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 150, "name" => "Turbografx-16/PC Engine CD", "slug" => "turbografx-16-slash-pc-engine-cd", "generation" => null, "abbreviation" => null, "alternative_name" => "TG-16CD/PCECD", "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 156, "name" => "Thomson MO5", "slug" => "thomson-mo5", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 148, "name" => "AY-3-8607", "slug" => "ay-3-8607", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 309, "name" => "Evercade", "slug" => "evercade", "generation" => 8, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 389, "name" => "AirConsole", "slug" => "airconsole", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 3],
        ["platform_id" => 112, "name" => "Microcomputer", "slug" => "microcomputer--1", "generation" => null, "abbreviation" => "microcomputer", "alternative_name" => null, "summary" => null, "platform_type_id" => null],
        ["platform_id" => 41, "name" => "Wii U", "slug" => "wiiu", "generation" => 8, "abbreviation" => "WiiU", "alternative_name" => "Project Cafe", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 13, "name" => "DOS", "slug" => "dos", "generation" => null, "abbreviation" => "DOS", "alternative_name" => "PC DOS", "summary" => null, "platform_type_id" => 4],
        ["platform_id" => 60, "name" => "Atari 7800", "slug" => "atari7800", "generation" => 3, "abbreviation" => "Atari7800", "alternative_name" => "Atari 7800 ProSystem", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 410, "name" => "Atari Jaguar CD", "slug" => "atari-jaguar-cd", "generation" => 5, "abbreviation" => null, "alternative_name" => "Jag CD", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 127, "name" => "Fairchild Channel F", "slug" => "fairchild-channel-f", "generation" => 2, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 30, "name" => "Sega 32X", "slug" => "sega32", "generation" => 4, "abbreviation" => "Sega32", "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 53, "name" => "MSX2", "slug" => "msx2", "generation" => null, "abbreviation" => "MSX2", "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 77, "name" => "Sharp X1", "slug" => "x1", "generation" => null, "abbreviation" => "x1", "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 132, "name" => "Amazon Fire TV", "slug" => "amazon-fire-tv", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 3],
        ["platform_id" => 120, "name" => "Neo Geo Pocket Color", "slug" => "neo-geo-pocket-color", "generation" => 5, "abbreviation" => null, "alternative_name" => "NGPC", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 61, "name" => "Atari Lynx", "slug" => "lynx", "generation" => 4, "abbreviation" => "Lynx", "alternative_name" => null, "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 413, "name" => "Leapster Explorer/LeadPad Explorer", "slug" => "leapster-explorer-slash-leadpad-explorer", "generation" => 7, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 153, "name" => "Dragon 32/64", "slug" => "dragon-32-slash-64", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 140, "name" => "AY-3-8500", "slug" => "ay-3-8500", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 143, "name" => "AY-3-8760", "slug" => "ay-3-8760", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 154, "name" => "Amstrad PCW", "slug" => "amstrad-pcw", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 167, "name" => "PlayStation 5", "slug" => "ps5", "generation" => 9, "abbreviation" => "PS5", "alternative_name" => "PS5", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 70, "name" => "Vectrex", "slug" => "vectrex", "generation" => 2, "abbreviation" => "vectrex", "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 145, "name" => "AY-3-8603", "slug" => "ay-3-8603", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 87, "name" => "Virtual Boy", "slug" => "virtualboy", "generation" => 5, "abbreviation" => "virtualboy", "alternative_name" => "VB", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 386, "name" => "Meta Quest 2", "slug" => "meta-quest-2", "generation" => null, "abbreviation" => "Meta Quest 2", "alternative_name" => "Quest 2", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 390, "name" => "PlayStation VR2", "slug" => "psvr2", "generation" => 9, "abbreviation" => "PSVR2", "alternative_name" => "PSVR2", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 477, "name" => "Panasonic Jungle", "slug" => "panasonic-jungle", "generation" => 8, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 504, "name" => "Uzebox", "slug" => "uzebox", "generation" => null, "abbreviation" => null, "alternative_name" => "EUzebox", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 65, "name" => "Atari 8-bit", "slug" => "atari8bit", "generation" => null, "abbreviation" => "Atari8bit", "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 158, "name" => "Commodore CDTV", "slug" => "commodore-cdtv", "generation" => null, "abbreviation" => null, "alternative_name" => "Commodore Dynamic Total Vision", "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 165, "name" => "PlayStation VR", "slug" => "psvr", "generation" => 8, "abbreviation" => "PSVR", "alternative_name" => "PSVR", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 440, "name" => "Visual Memory Unit / Visual Memory System", "slug" => "visual-memory-unit-slash-visual-memory-system", "generation" => 6, "abbreviation" => null, "alternative_name" => "VMU / VMS", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 473, "name" => "Arcadia 2001", "slug" => "arcadia-2001", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 474, "name" => "Gizmondo", "slug" => "gizmondo", "generation" => 7, "abbreviation" => null, "alternative_name" => "Gametraq", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 94, "name" => "Commodore Plus/4", "slug" => "c-plus-4", "generation" => null, "abbreviation" => "C+4", "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 123, "name" => "WonderSwan Color", "slug" => "wonderswan-color", "generation" => 5, "abbreviation" => null, "alternative_name" => "WSC", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 128, "name" => "PC Engine SuperGrafx", "slug" => "supergrafx", "generation" => 4, "abbreviation" => "supergrafx", "alternative_name" => "SuperGrafx", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 129, "name" => "Texas Instruments TI-99", "slug" => "ti-99", "generation" => null, "abbreviation" => "ti-99", "alternative_name" => "Texas Instruments TI-99/4A", "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 89, "name" => "Microvision", "slug" => "microvision--1", "generation" => 2, "abbreviation" => "microvision", "alternative_name" => null, "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 48, "name" => "PlayStation 4", "slug" => "ps4--1", "generation" => 8, "abbreviation" => "PS4", "alternative_name" => "PS4", "summary" => "The PlayStation 4 system opens the door to an incredible journey through immersive new gaming worlds and a deeply connected gaming community. PS4 puts gamers first with an astounding launch line-up and over 180 games in development. Play amazing top-tier blockbusters and innovative indie hits on PS4. Developer inspired, gamer focused.", "platform_type_id" => 1],
        ["platform_id" => 51, "name" => "Family Computer Disk System", "slug" => "fds", "generation" => 3, "abbreviation" => "fds", "alternative_name" => "Famicom Disk System, FDS", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 482, "name" => "Sega CD 32X", "slug" => "sega-cd-32x", "generation" => 4, "abbreviation" => null, "alternative_name" => "Sega Mega-CD 32X", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 6, "name" => "PC (Microsoft Windows)", "slug" => "win", "generation" => null, "abbreviation" => "PC", "alternative_name" => "mswin", "summary" => null, "platform_type_id" => 4],
        ["platform_id" => 134, "name" => "Acorn Electron", "slug" => "acorn-electron", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 8, "name" => "PlayStation 2", "slug" => "ps2", "generation" => 6, "abbreviation" => "PS2", "alternative_name" => "PS2", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 136, "name" => "Neo Geo CD", "slug" => "neo-geo-cd", "generation" => 4, "abbreviation" => null, "alternative_name" => "NGCD", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 23, "name" => "Dreamcast", "slug" => "dc", "generation" => 6, "abbreviation" => "DC", "alternative_name" => "DC", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 35, "name" => "Sega Game Gear", "slug" => "gamegear", "generation" => 4, "abbreviation" => "Game Gear", "alternative_name" => "GG", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 44, "name" => "Tapwave Zodiac", "slug" => "zod", "generation" => null, "abbreviation" => "zod", "alternative_name" => null, "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 88, "name" => "Odyssey", "slug" => "odyssey--1", "generation" => 1, "abbreviation" => "odyssey", "alternative_name" => "Magnavox Odyssey; Odysee; Odisea; Odissea", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 97, "name" => "PDP-8", "slug" => "pdp-8--1", "generation" => null, "abbreviation" => "pdp-8", "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 39, "name" => "iOS", "slug" => "ios", "generation" => null, "abbreviation" => "iOS", "alternative_name" => null, "summary" => null, "platform_type_id" => 4],
        ["platform_id" => 3, "name" => "Linux", "slug" => "linux", "generation" => null, "abbreviation" => "Linux", "alternative_name" => "GNU/Linux", "summary" => "Linux is a free and open-source (FOSS/FLOSS) Operating System. In a more precise and complex definition, Linux is an open-source OS kernel on which a large variety of Operating Systems (known as Linux distributions) are built.", "platform_type_id" => 4],
        ["platform_id" => 373, "name" => "Sinclair ZX81", "slug" => "sinclair-zx81", "generation" => null, "abbreviation" => null, "alternative_name" => "ZX81", "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 505, "name" => "Elektor TV Games Computer", "slug" => "elektor-tv-games-computer", "generation" => null, "abbreviation" => null, "alternative_name" => "TVGC", "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 133, "name" => "Odyssey 2 / Videopac G7000", "slug" => "odyssey-2-slash-videopac-g7000", "generation" => null, "abbreviation" => null, "alternative_name" => "Magnavox Odyssey²", "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 135, "name" => "Hyper Neo Geo 64", "slug" => "hyper-neo-geo-64", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 2],
        ["platform_id" => 142, "name" => "PC-50X Family", "slug" => "pc-50x-family", "generation" => 1, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 144, "name" => "AY-3-8710", "slug" => "ay-3-8710", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 146, "name" => "AY-3-8605", "slug" => "ay-3-8605", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 147, "name" => "AY-3-8606", "slug" => "ay-3-8606", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 149, "name" => "PC-9800 Series", "slug" => "pc-9800-series", "generation" => null, "abbreviation" => null, "alternative_name" => "PC-98", "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 163, "name" => "SteamVR", "slug" => "steam-vr", "generation" => null, "abbreviation" => "Steam VR", "alternative_name" => null, "summary" => null, "platform_type_id" => null],
        ["platform_id" => 237, "name" => "Sol-20", "slug" => "sol-20", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 85, "name" => "Donner Model 30", "slug" => "donner30", "generation" => null, "abbreviation" => "donner30", "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 24, "name" => "Game Boy Advance", "slug" => "gba", "generation" => 6, "abbreviation" => "GBA", "alternative_name" => "GBA", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 78, "name" => "Sega CD", "slug" => "segacd", "generation" => 4, "abbreviation" => "segacd", "alternative_name" => "Mega CD", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 115, "name" => "Apple IIGS", "slug" => "apple-iigs", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 119, "name" => "Neo Geo Pocket", "slug" => "neo-geo-pocket", "generation" => 5, "abbreviation" => null, "alternative_name" => "NGP", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 125, "name" => "PC-8800 Series", "slug" => "pc-8800-series", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 72, "name" => "Ouya", "slug" => "ouya", "generation" => 8, "abbreviation" => "Ouya", "alternative_name" => null, "summary" => "The Ouya (/ˈuːjə/ oo-yə), stylized OUYA, is a microconsole running its own version of the Android operating system, developed by Ouya Inc. Julie Uhrman founded the project in 2012. She brought in designer Yves Béhar to collaborate on the design of the project, and Muffi Ghadiali as product manager to put together the engineering team. Development was funded via Kickstarter, raising $8.5 million and becoming the website's second-highest-earning project in its history.

Units started to ship to Kickstarter backers on March 28, 2013. The console was released to the general public on June 25, 2013, and features an exclusive Ouya store for applications and games designed specifically for the Ouya platform, of which the majority are casual games targeted at or used by a mass audience of casual gamers. Out of the box, Ouya supports media apps such as TwitchTV and XBMC media player. It runs a modified version of Android 4.1 Jelly Bean, and is open to rooting without voiding the warranty (developer models ordered during the Kickstarter campaign for $699 or $1,337 come pre-rooted). The console's hardware design allows it to be easily opened up, requiring only a standard screwdriver for easy modding and possible hardware addons.

All systems can be used as development kits, allowing any Ouya owner to also be a developer, without the need for licensing fees. All games are required to have some kind of free-to-play aspect, whether that be completely free, has a free trial, or has purchasable upgrades, levels, or other in-game items. The Ouya is classified as part of the eighth generation of video game consoles and as such is a rival competing against the PlayStation 4, Xbox One, and Wii U.", "platform_type_id" => 1],
        ["platform_id" => 101, "name" => "Ferranti Nimrod Computer", "slug" => "nimrod", "generation" => null, "abbreviation" => "nimrod", "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 108, "name" => "PDP-11", "slug" => "pdp11", "generation" => null, "abbreviation" => "pdp11", "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 109, "name" => "CDC Cyber 70", "slug" => "cdccyber70", "generation" => null, "abbreviation" => "cdccyber70", "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 113, "name" => "OnLive Game System", "slug" => "onlive-game-system", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 3],
        ["platform_id" => 98, "name" => "DEC GT40", "slug" => "gt40", "generation" => null, "abbreviation" => "gt40", "alternative_name" => null, "summary" => null, "platform_type_id" => null],
        ["platform_id" => 124, "name" => "SwanCrystal", "slug" => "swancrystal", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 138, "name" => "VC 4000", "slug" => "vc-4000", "generation" => 2, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 139, "name" => "1292 Advanced Programmable Video System", "slug" => "1292-advanced-programmable-video-system", "generation" => 2, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 155, "name" => "Tatung Einstein", "slug" => "tatung-einstein", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 46, "name" => "PlayStation Vita", "slug" => "psvita", "generation" => 8, "abbreviation" => "Vita", "alternative_name" => "PS Vita", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 66, "name" => "Atari 5200", "slug" => "atari5200", "generation" => 2, "abbreviation" => "Atari5200", "alternative_name" => "Atari 5200 SuperSystem", "summary" => "the mother text", "platform_type_id" => 1],
        ["platform_id" => 9, "name" => "PlayStation 3", "slug" => "ps3", "generation" => 7, "abbreviation" => "PS3", "alternative_name" => "PS3", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 11, "name" => "Xbox", "slug" => "xbox", "generation" => 6, "abbreviation" => "XBOX", "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 111, "name" => "Imlac PDS-1", "slug" => "imlac-pds1", "generation" => null, "abbreviation" => "imlac-pds1", "alternative_name" => null, "summary" => null, "platform_type_id" => null],
        ["platform_id" => 15, "name" => "Commodore C64/128/MAX", "slug" => "c64", "generation" => null, "abbreviation" => "C64", "alternative_name" => "C64/C128/MAX", "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 18, "name" => "Nintendo Entertainment System", "slug" => "nes", "generation" => 3, "abbreviation" => "NES", "alternative_name" => "NES", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 162, "name" => "Oculus VR", "slug" => "oculus-vr", "generation" => null, "abbreviation" => "Oculus VR", "alternative_name" => null, "summary" => null, "platform_type_id" => null],
        ["platform_id" => 67, "name" => "Intellivision", "slug" => "intellivision", "generation" => 2, "abbreviation" => "intellivision", "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 20, "name" => "Nintendo DS", "slug" => "nds", "generation" => 7, "abbreviation" => "NDS", "alternative_name" => "NDS", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 22, "name" => "Game Boy Color", "slug" => "gbc", "generation" => 5, "abbreviation" => "GBC", "alternative_name" => "GBC", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 32, "name" => "Sega Saturn", "slug" => "saturn", "generation" => 5, "abbreviation" => "Saturn", "alternative_name" => "JVC Saturn, Hi-Saturn, Samsung Saturn, V-Saturn", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 131, "name" => "Super NES CD-ROM System", "slug" => "super-nes-cd-rom-system", "generation" => 4, "abbreviation" => null, "alternative_name" => "SNES-CD", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 73, "name" => "BlackBerry OS", "slug" => "blackberry", "generation" => null, "abbreviation" => "blackberry", "alternative_name" => null, "summary" => null, "platform_type_id" => 4],
        ["platform_id" => 114, "name" => "Amiga CD32", "slug" => "amiga-cd32", "generation" => 5, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 116, "name" => "Acorn Archimedes", "slug" => "acorn-archimedes", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 117, "name" => "Philips CD-i", "slug" => "philips-cd-i", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 118, "name" => "FM Towns", "slug" => "fm-towns", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 121, "name" => "Sharp X68000", "slug" => "sharp-x68000", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 152, "name" => "FM-7", "slug" => "fm-7", "generation" => null, "abbreviation" => null, "alternative_name" => "Fujitsu Micro 7", "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 157, "name" => "NEC PC-6000 Series", "slug" => "nec-pc-6000-series", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 86, "name" => "TurboGrafx-16/PC Engine", "slug" => "turbografx16--1", "generation" => 4, "abbreviation" => "turbografx16", "alternative_name" => "TG16", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 307, "name" => "Game & Watch", "slug" => "g-and-w", "generation" => 2, "abbreviation" => "G&W", "alternative_name" => "Tricotronic, GW, G&W", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 308, "name" => "Playdia", "slug" => "playdia", "generation" => 5, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 506, "name" => "Amstrad GX4000", "slug" => "amstrad-gx4000", "generation" => 3, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 122, "name" => "Nuon", "slug" => "nuon", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 141, "name" => "AY-3-8610", "slug" => "ay-3-8610", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 42, "name" => "N-Gage", "slug" => "ngage", "generation" => 6, "abbreviation" => "NGage", "alternative_name" => "NGage", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 170, "name" => "Google Stadia", "slug" => "stadia", "generation" => null, "abbreviation" => "Stadia", "alternative_name" => "Stadia", "summary" => null, "platform_type_id" => 3],
        ["platform_id" => 161, "name" => "Windows Mixed Reality", "slug" => "windows-mixed-reality", "generation" => null, "abbreviation" => null, "alternative_name" => "WMR", "summary" => null, "platform_type_id" => null],
        ["platform_id" => 57, "name" => "WonderSwan", "slug" => "wonderswan", "generation" => 5, "abbreviation" => "WonderSwan", "alternative_name" => "WS", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 69, "name" => "BBC Microcomputer System", "slug" => "bbcmicro", "generation" => null, "abbreviation" => "bbcmicro", "alternative_name" => "BBC Micro", "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 71, "name" => "Commodore VIC-20", "slug" => "vic-20", "generation" => null, "abbreviation" => "vic-20", "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 74, "name" => "Windows Phone", "slug" => "winphone", "generation" => null, "abbreviation" => "Win Phone", "alternative_name" => "WP", "summary" => null, "platform_type_id" => 4],
        ["platform_id" => 21, "name" => "Nintendo GameCube", "slug" => "ngc", "generation" => 6, "abbreviation" => "NGC", "alternative_name" => "GCN", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 33, "name" => "Game Boy", "slug" => "gb", "generation" => 4, "abbreviation" => "Game Boy", "alternative_name" => "GB", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 79, "name" => "Neo Geo MVS", "slug" => "neogeomvs", "generation" => null, "abbreviation" => "neogeomvs", "alternative_name" => "Neo Geo Multi Video System", "summary" => null, "platform_type_id" => 2],
        ["platform_id" => 80, "name" => "Neo Geo AES", "slug" => "neogeoaes", "generation" => 4, "abbreviation" => "neogeoaes", "alternative_name" => "AES", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 84, "name" => "SG-1000", "slug" => "sg1000", "generation" => 3, "abbreviation" => "sg1000", "alternative_name" => "Sega Game 1000", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 91, "name" => "Bally Astrocade", "slug" => "astrocade", "generation" => 2, "abbreviation" => "astrocade", "alternative_name" => "Bally Arcade", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 93, "name" => "Commodore 16", "slug" => "c16", "generation" => null, "abbreviation" => "C16", "alternative_name" => "C16", "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 96, "name" => "PDP-10", "slug" => "pdp10", "generation" => null, "abbreviation" => "pdp10", "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 103, "name" => "PDP-7", "slug" => "pdp-7--1", "generation" => null, "abbreviation" => "pdp-7", "alternative_name" => null, "summary" => null, "platform_type_id" => null],
        ["platform_id" => 38, "name" => "PlayStation Portable", "slug" => "psp", "generation" => 7, "abbreviation" => "PSP", "alternative_name" => "PSP", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 137, "name" => "New Nintendo 3DS", "slug" => "new-nintendo-3ds", "generation" => 8, "abbreviation" => null, "alternative_name" => "n3DS", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 374, "name" => "Sharp MZ-2200", "slug" => "sharp-mz-2200", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 375, "name" => "Epoch Cassette Vision", "slug" => "epoch-cassette-vision", "generation" => 2, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 377, "name" => "Plug & Play", "slug" => "plug-and-play", "generation" => null, "abbreviation" => null, "alternative_name" => "TV Game", "summary" => null, "platform_type_id" => 3],
        ["platform_id" => 379, "name" => "Game.com", "slug" => "game-dot-com", "generation" => 5, "abbreviation" => null, "alternative_name" => "Tiger Game.com", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 382, "name" => "Intellivision Amico", "slug" => "intellivision-amico", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 384, "name" => "Oculus Quest", "slug" => "oculus-quest", "generation" => null, "abbreviation" => null, "alternative_name" => "Quest", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 385, "name" => "Oculus Rift", "slug" => "oculus-rift", "generation" => null, "abbreviation" => null, "alternative_name" => "Rift", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 387, "name" => "Oculus Go", "slug" => "oculus-go", "generation" => null, "abbreviation" => null, "alternative_name" => "Go", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 388, "name" => "Gear VR", "slug" => "gear-vr", "generation" => null, "abbreviation" => null, "alternative_name" => "Samsung Gear VR", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 479, "name" => "Terebikko / See 'n Say Video Phone", "slug" => "terebikko-slash-see-n-say-video-phone", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 507, "name" => "Advanced Pico Beena", "slug" => "advanced-pico-beena", "generation" => 6, "abbreviation" => null, "alternative_name" => "BeenaLite", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 508, "name" => "Nintendo Switch 2", "slug" => "nintendo-switch-2", "generation" => 9, "abbreviation" => null, "alternative_name" => "Switch 2", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 50, "name" => "3DO Interactive Multiplayer", "slug" => "3do", "generation" => 5, "abbreviation" => "3DO", "alternative_name" => "3DO", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 169, "name" => "Xbox Series X|S", "slug" => "series-x-s", "generation" => 9, "abbreviation" => "Series X|S", "alternative_name" => "XSX", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 64, "name" => "Sega Master System/Mark III", "slug" => "sms", "generation" => 3, "abbreviation" => "SMS", "alternative_name" => "SMS, Mark III", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 151, "name" => "TRS-80 Color Computer", "slug" => "trs-80-color-computer", "generation" => null, "abbreviation" => null, "alternative_name" => "Tandy Color Computer", "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 238, "name" => "DVD Player", "slug" => "dvd-player", "generation" => null, "abbreviation" => null, "alternative_name" => "Digital Versatile Disc Player", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 274, "name" => "PC-FX", "slug" => "pc-fx", "generation" => 5, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 26, "name" => "ZX Spectrum", "slug" => "zxs", "generation" => null, "abbreviation" => "ZXS", "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 27, "name" => "MSX", "slug" => "msx", "generation" => null, "abbreviation" => "MSX", "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 37, "name" => "Nintendo 3DS", "slug" => "3ds", "generation" => 8, "abbreviation" => "3DS", "alternative_name" => "3DS", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 240, "name" => "Zeebo", "slug" => "zeebo", "generation" => 7, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 95, "name" => "PDP-1", "slug" => "pdp1", "generation" => null, "abbreviation" => "pdp1", "alternative_name" => "Programmed Data Processor-1", "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 166, "name" => "Pokémon mini", "slug" => "pokemon-mini", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 203, "name" => "DUPLICATE Stadia", "slug" => "duplicate-stadia", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => null],
        ["platform_id" => 110, "name" => "PLATO", "slug" => "plato--1", "generation" => null, "abbreviation" => "plato", "alternative_name" => "Programmed Logic for Automatic Teaching Operations", "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 164, "name" => "Daydream", "slug" => "daydream", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => null],
        ["platform_id" => 100, "name" => "Analogue electronics", "slug" => "analogueelectronics", "generation" => null, "abbreviation" => "analogueelectronics", "alternative_name" => null, "summary" => null, "platform_type_id" => null],
        ["platform_id" => 236, "name" => "Exidy Sorcerer", "slug" => "exidy-sorcerer", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 102, "name" => "EDSAC", "slug" => "edsac--1", "generation" => null, "abbreviation" => "edsac", "alternative_name" => "Electronic Delay Storage Automatic Calculator", "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 104, "name" => "HP 2100", "slug" => "hp2100", "generation" => null, "abbreviation" => "hp2100", "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 105, "name" => "HP 3000", "slug" => "hp3000", "generation" => null, "abbreviation" => "hp3000", "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 106, "name" => "SDS Sigma 7", "slug" => "sdssigma7", "generation" => null, "abbreviation" => "sdssigma7", "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 107, "name" => "Call-A-Computer time-shared mainframe computer system", "slug" => "call-a-computer", "generation" => null, "abbreviation" => "call-a-computer", "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 239, "name" => "Blu-ray Player", "slug" => "blu-ray-player", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 99, "name" => "Family Computer", "slug" => "famicom", "generation" => 3, "abbreviation" => "famicom", "alternative_name" => "Famicom", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 372, "name" => "OOParts", "slug" => "ooparts", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 3],
        ["platform_id" => 378, "name" => "Gamate", "slug" => "gamate", "generation" => 4, "abbreviation" => null, "alternative_name" => "Super Boy", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 380, "name" => "Casio Loopy", "slug" => "casio-loopy", "generation" => null, "abbreviation" => null, "alternative_name" => "Loopy", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 381, "name" => "Playdate", "slug" => "playdate", "generation" => 9, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 411, "name" => "Handheld Electronic LCD", "slug" => "handheld-electronic-lcd", "generation" => null, "abbreviation" => null, "alternative_name" => "Handheld LCD Game", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 415, "name" => "Watara/QuickShot Supervision", "slug" => "watara-slash-quickshot-supervision", "generation" => 4, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 478, "name" => "Panasonic M2", "slug" => "panasonic-m2", "generation" => 6, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 486, "name" => "Digiblast", "slug" => "digiblast", "generation" => 7, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 509, "name" => "Polymega", "slug" => "polymega", "generation" => null, "abbreviation" => null, "alternative_name" => "RetroBlox", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 7, "name" => "PlayStation", "slug" => "ps", "generation" => 5, "abbreviation" => "PS1", "alternative_name" => "PSX, PSOne, PS", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 16, "name" => "Amiga", "slug" => "amiga", "generation" => null, "abbreviation" => "Amiga", "alternative_name" => "Commodore Amiga", "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 47, "name" => "Virtual Console", "slug" => "vc", "generation" => null, "abbreviation" => "VC", "alternative_name" => "VC", "summary" => null, "platform_type_id" => 3],
        ["platform_id" => 52, "name" => "Arcade", "slug" => "arcade", "generation" => null, "abbreviation" => "Arcade", "alternative_name" => null, "summary" => null, "platform_type_id" => 2],
        ["platform_id" => 59, "name" => "Atari 2600", "slug" => "atari2600", "generation" => 2, "abbreviation" => "Atari2600", "alternative_name" => "Atari VCS", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 12, "name" => "Xbox 360", "slug" => "xbox360", "generation" => 7, "abbreviation" => "X360", "alternative_name" => "X360", "summary" => "Xbox 360 brings you a total games and entertainment experience. The largest library of games, including titles that get you right into the thick of it with Kinect. Plus, your whole family can watch HD movies, TV shows, live events, music, sports and more—across all your devices. Xbox 360 is the center of your games and entertainment universe.", "platform_type_id" => 1],
        ["platform_id" => 68, "name" => "ColecoVision", "slug" => "colecovision", "generation" => 2, "abbreviation" => "colecovision", "alternative_name" => "Coleco", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 25, "name" => "Amstrad CPC", "slug" => "acpc", "generation" => null, "abbreviation" => "ACPC", "alternative_name" => "Colour Personal Computer", "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 29, "name" => "Sega Mega Drive/Genesis", "slug" => "genesis-slash-megadrive", "generation" => 4, "abbreviation" => "Genesis/MegaDrive", "alternative_name" => "Sega Genesis", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 34, "name" => "Android", "slug" => "android", "generation" => null, "abbreviation" => "Android", "alternative_name" => "Infocusa3", "summary" => null, "platform_type_id" => 4],
        ["platform_id" => 405, "name" => "Windows Mobile", "slug" => "windows-mobile", "generation" => null, "abbreviation" => null, "alternative_name" => "Pocket PC", "summary" => null, "platform_type_id" => 4],
        ["platform_id" => 406, "name" => "Sinclair QL", "slug" => "sinclair-ql", "generation" => null, "abbreviation" => null, "alternative_name" => "Sinclair Quantum Leap", "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 407, "name" => "HyperScan", "slug" => "hyperscan", "generation" => 7, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 408, "name" => "Mega Duck/Cougar Boy", "slug" => "mega-duck-slash-cougar-boy", "generation" => 4, "abbreviation" => null, "alternative_name" => "WG-108", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 409, "name" => "Legacy Computer", "slug" => "legacy-computer", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 412, "name" => "Leapster", "slug" => "leapster", "generation" => 6, "abbreviation" => null, "alternative_name" => "Leapster Learning Game System", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 414, "name" => "LeapTV", "slug" => "leaptv", "generation" => 8, "abbreviation" => null, "alternative_name" => "LeapTV VCD", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 416, "name" => "64DD", "slug" => "64dd", "generation" => 5, "abbreviation" => null, "alternative_name" => "Nintendo 64DD", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 417, "name" => "Palm OS", "slug" => "palm-os", "generation" => null, "abbreviation" => null, "alternative_name" => "Garnet OS", "summary" => null, "platform_type_id" => 4],
        ["platform_id" => 438, "name" => "Arduboy", "slug" => "arduboy", "generation" => 8, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 439, "name" => "V.Smile", "slug" => "vsmile", "generation" => 6, "abbreviation" => null, "alternative_name" => "V.SMILE TV LEARNING SYSTEM", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 441, "name" => "PocketStation", "slug" => "pocketstation", "generation" => 5, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 471, "name" => "Meta Quest 3", "slug" => "meta-quest-3", "generation" => 9, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 472, "name" => "visionOS", "slug" => "visionos", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 4],
        ["platform_id" => 475, "name" => "R-Zone", "slug" => "r-zone", "generation" => 5, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 476, "name" => "Apple Pippin", "slug" => "apple-pippin", "generation" => 5, "abbreviation" => null, "alternative_name" => "PiPP!N", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 480, "name" => "Super A'Can", "slug" => "super-acan", "generation" => 4, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 481, "name" => "Tomy Tutor / Pyuta / Grandstand Tutor", "slug" => "tomy-tutor-slash-pyuta-slash-grandstand-tutor", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 49, "name" => "Xbox One", "slug" => "xboxone", "generation" => 8, "abbreviation" => "XONE", "alternative_name" => "XONE", "summary" => "Welcome to a new generation of games and entertainment. Where games push the boundaries of realism. And television obeys your every command. Where listening to music while playing a game is a snap. And you can jump from TV to movies to music to a game in an instant. Where your experience is custom tailored to you. And the entertainment you love is all in one place. Welcome to the all-in-one, Xbox One", "platform_type_id" => 1],
        ["platform_id" => 55, "name" => "Legacy Mobile Device", "slug" => "mobile", "generation" => null, "abbreviation" => "Mobile", "alternative_name" => "Legacy Cellphone", "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 58, "name" => "Super Famicom", "slug" => "sfam", "generation" => 4, "abbreviation" => "SFAM", "alternative_name" => "SFC", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 4, "name" => "Nintendo 64", "slug" => "n64", "generation" => 5, "abbreviation" => "N64", "alternative_name" => "N64", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 63, "name" => "Atari ST/STE", "slug" => "atari-st", "generation" => null, "abbreviation" => "Atari-ST", "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 75, "name" => "Apple II", "slug" => "appleii", "generation" => null, "abbreviation" => "Apple][", "alternative_name" => "apple ][", "summary" => "The Apple II is an 8-bit home computer, one of the first highly successful mass-produced microcomputer products, designed primarily by Steve Wozniak, manufactured by Apple Computer (now Apple Inc.) and introduced in 1977. It is the first model in a series of computers which were produced until Apple IIe production ceased in November 1993.", "platform_type_id" => 6],
        ["platform_id" => 82, "name" => "Web browser", "slug" => "browser", "generation" => null, "abbreviation" => "browser", "alternative_name" => "Internet", "summary" => null, "platform_type_id" => 3],
        ["platform_id" => 90, "name" => "Commodore PET", "slug" => "cpet", "generation" => null, "abbreviation" => "cpet", "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 126, "name" => "TRS-80", "slug" => "trs-80", "generation" => null, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 6],
        ["platform_id" => 159, "name" => "Nintendo DSi", "slug" => "nintendo-dsi", "generation" => 7, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 5],
        ["platform_id" => 5, "name" => "Wii", "slug" => "wii", "generation" => 7, "abbreviation" => "Wii", "alternative_name" => "Revolution", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 14, "name" => "Mac", "slug" => "mac", "generation" => null, "abbreviation" => "Mac", "alternative_name" => "Mac OS", "summary" => null, "platform_type_id" => 4],
        ["platform_id" => 19, "name" => "Super Nintendo Entertainment System", "slug" => "snes", "generation" => 4, "abbreviation" => "SNES", "alternative_name" => "SNES, Super Nintendo", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 130, "name" => "Nintendo Switch", "slug" => "switch", "generation" => 8, "abbreviation" => "Switch", "alternative_name" => "NX", "summary" => null, "platform_type_id" => 1],
        ["platform_id" => 487, "name" => "LaserActive", "slug" => "laseractive", "generation" => 4, "abbreviation" => null, "alternative_name" => null, "summary" => null, "platform_type_id" => 1],
    ];
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach (self::__PLATFORM__ as $platform) {
            Platform::create($platform);
        }
    }
}
